import "bootstrap/dist/css/bootstrap.css"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ankasa Ticketing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/img/fly.png" type="image/png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
